### PR TITLE
Device Explorer Utility link modified

### PR DESCRIPTION
**Pull request by mohan08p**
The respective link for the Device Explorer utility is modified as the current link was broken.

Signed-off By : Mohan Pawar <mohanpawary1990@gmail.com>

### CODE REVIEW

**Comment by saurabhkirtani** [comment]
Thanks @mohan08p for pointing this out. A couple of things:

- To setup IoT Hub explorer, you've specified the Azure portal link directly. The official docs contain steps on how to create a new IoT hub from the portal. Can you update this link? Here: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-node-node-getstarted#create-an-iot-hub

- The link you've provided to download Device Explorer is correct. However, [this](https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/DeviceExplorer) link contains step by step instructions on how to use the utility, which will be useful for someone following this lab at their own pace. Can you update this?

Thanks.

**Comment by mohan08p** [comment]
@saurabhkirtani : thanks. the changes made accordingly. :+1:

**Comment by saurabhkirtani** [comment]
@mohan08p You've made the correct edit for point 11. However, for point 12, you've added relevant Device Explorer link in the explanation for iothub-explorer. 
The URL for iothub-explorer was correct earlier.
Can you make these edits?

**Comment by mohan08p** [comment]
@saurabhkirtani : Ohh..  Can you just check, that link redirect to 404.  Is this the correct one ? https://github.com/Azure/iothub-explorer

**Comment by saurabhkirtani** [comment]
Device explorer is [here](https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/DeviceExplorer).
iothub-explorer is [here](https://github.com/Azure/iothub-explorer).

**Pull request merged**
